// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mndxzewzaxfhdgzhpghw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZHh6ZXd6YXhmaGRnemhwZ2h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTUxMzgsImV4cCI6MjA3NDM3MTEzOH0.nCKroHXLDIIYDbe8U5vv9YqZ2WYtmmMVDsc7wG6bXCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});